[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-custom.variants.design]
capital-g = "toothless-corner-serifless-hookless"
capital-q = "crossing"
a = "single-storey-serifless"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
zero = "dotted"
asterisk = "penta-low"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"

  [buildPlans.iosevka-custom.ligations]
  inherits = "dlig"
