# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "41bbe19d1a1a7eaab5e7bb9050a417e5c6cffc8f";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "41bbe19d1a1a7eaab5e7bb9050a417e5c6cffc8f";
      fetchSubmodules = false;
      sha256 = "sha256-sjgPv9tZZVTXPxZWaCOc7JwFceNn3C1ghy8mSHqgqB8=";
    };
    date = "2026-09-03";
  };
  beets-fetchartist = {
    pname = "beets-fetchartist";
    version = "d002de427f39b1bf6b7173a87c069c4a6cf9970d";
    src = fetchFromGitHub {
      owner = "ttoino";
      repo = "beets-fetchartist";
      rev = "d002de427f39b1bf6b7173a87c069c4a6cf9970d";
      fetchSubmodules = false;
      sha256 = "sha256-tRlnzLkMnL3td1L2kjUeoXPmmCStuZp49TrhmGICuTU=";
    };
    date = "2025-10-07";
  };
  caddy-cloudflare = {
    pname = "caddy-cloudflare";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "caddy-dns";
      repo = "cloudflare";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-0Csi6WmyoGj7bXeo2Lrnwr0SCoV6c/niymtOp5DdiT4=";
    };
  };
  cloudflare-skills = {
    pname = "cloudflare-skills";
    version = "d924cd8f59e75e08fd3dd52843bb2776de35c77e";
    src = fetchFromGitHub {
      owner = "cloudflare";
      repo = "skills";
      rev = "d924cd8f59e75e08fd3dd52843bb2776de35c77e";
      fetchSubmodules = false;
      sha256 = "sha256-DdIutn1688pRbzl+tOHpbyChfw1cyCyng+FqJk6P85s=";
    };
    date = "2026-09-05";
  };
  lidarr-plugins = {
    pname = "lidarr-plugins";
    version = "0842f73cf495fe0536e07c765d6fe55b5ece0c0f";
    src = fetchFromGitHub {
      owner = "lidarr";
      repo = "Lidarr";
      rev = "0842f73cf495fe0536e07c765d6fe55b5ece0c0f";
      fetchSubmodules = false;
      sha256 = "sha256-iRUXWJD8oQ/eWfwR0TvC2NA5JWNqW61x9uORlAHz/jk=";
    };
    date = "2025-12-28";
  };
  meterial-symbols = {
    pname = "meterial-symbols";
    version = "v1.3.0";
    src = fetchurl {
      url = "https://github.com/ttoino/meterial-symbols/releases/download/v1.3.0/MeterialSymbols.zip";
      sha256 = "sha256-Du2eGckhC6lJpAhebBbAINST1OIDCn3biU/LYx+eVxU=";
    };
  };
  mopidy-dynamic = {
    pname = "mopidy-dynamic";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/M/Mopidy-Dynamic/mopidy_dynamic-1.0.0-py3-none-any.whl";
      sha256 = "sha256-kcUZpLg3/nhcWN5Y91umD1yON1j0Y/arMr2J2gGNGBY=";
    };
  };
  mopidy-local = {
    pname = "mopidy-local";
    version = "3cf3b7c14235e1618c5f1cd0e6a5c1df3fd0d2e0";
    src = fetchFromGitHub {
      owner = "ttoino";
      repo = "mopidy-local";
      rev = "3cf3b7c14235e1618c5f1cd0e6a5c1df3fd0d2e0";
      fetchSubmodules = false;
      sha256 = "sha256-Em7Kk815lJqPrA8hFGc/q+WYA9b4XBqA6wQNO34M3C4=";
    };
    date = "2025-03-27";
  };
  mopidy-marceline = {
    pname = "mopidy-marceline";
    version = "0.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/M/Mopidy-Marceline/mopidy_marceline-0.0.5-py3-none-any.whl";
      sha256 = "sha256-/mBGeM0dk3jk8dJWKngLX0DokJht7pE0rhrajFSWksc=";
    };
  };
  mopidy-mpris = {
    pname = "mopidy-mpris";
    version = "c197be548a11f3efe012a705f0f906d2cc03708b";
    src = fetchFromGitHub {
      owner = "ttoino";
      repo = "mopidy-mpris";
      rev = "c197be548a11f3efe012a705f0f906d2cc03708b";
      fetchSubmodules = false;
      sha256 = "sha256-zrRJ4hS2bSNxjeEF4OnjOeXKsnY7V0Y6iKlUws+JjoY=";
    };
    date = "2025-05-19";
  };
  ohmyzsh = {
    pname = "ohmyzsh";
    version = "8a5b3930889ea9b99450e600b5b5e00d0170cc09";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "8a5b3930889ea9b99450e600b5b5e00d0170cc09";
      fetchSubmodules = false;
      sha256 = "sha256-b6MYs8bA/ZEYwuJQKO1AypqhI6WMP6wVHu6UqNh+mbM=";
    };
    date = "2026-09-05";
  };
  peon-dva = {
    pname = "peon-dva";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "leo-rutter";
      repo = "d.va-pack";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-YM4ge0j0HaZl1PMtmngx4qf1fJHLmr825bweezO5ZLQ=";
    };
  };
  peon-eve-walle = {
    pname = "peon-eve-walle";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "stphnlngdncoding";
      repo = "eve-walle";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-ujwutbgkY+DxEOJQeu0APuSgVWBLJj51N3kJEE/vmfM=";
    };
  };
  peon-jarvis-mk2 = {
    pname = "peon-jarvis-mk2";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "FlynnCruse";
      repo = "openpeon-jarvis";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-SDelu1fhg2/JFKIQM4lSLevl7wMUBfuAFNOM/5gf8Mo=";
    };
  };
  peon-minecraft-villager = {
    pname = "peon-minecraft-villager";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "Mahamurahti";
      repo = "openpeon-minecraft-villager";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-0vyWcgbdFcFwke8zSX3GSPETRX4fufeEXE2Dmks/9YE=";
    };
  };
  zsh-colored-man-pages = {
    pname = "zsh-colored-man-pages";
    version = "57bdda68e52a09075352b18fa3ca21abd31df4cb";
    src = fetchFromGitHub {
      owner = "ael-code";
      repo = "zsh-colored-man-pages";
      rev = "57bdda68e52a09075352b18fa3ca21abd31df4cb";
      fetchSubmodules = false;
      sha256 = "sha256-087bNmB5gDUKoSriHIjXOVZiUG5+Dy9qv3D69E8GBhs=";
    };
    date = "2019-04-02";
  };
  zsh-fast-syntax-highlighting = {
    pname = "zsh-fast-syntax-highlighting";
    version = "4672ad5dd9ad68a7effc1476d65afb7c584ce2b3";
    src = fetchFromGitHub {
      owner = "zdharma-continuum";
      repo = "fast-syntax-highlighting";
      rev = "4672ad5dd9ad68a7effc1476d65afb7c584ce2b3";
      fetchSubmodules = false;
      sha256 = "sha256-gXTJv+k4OSgwiM7vy91v7tLLHre0f5XeSor3n/b2euI=";
    };
    date = "2026-08-31";
  };
  zsh-gitstatus = {
    pname = "zsh-gitstatus";
    version = "v1.5.5";
    src = fetchFromGitHub {
      owner = "romkatv";
      repo = "gitstatus";
      rev = "v1.5.5";
      fetchSubmodules = false;
      sha256 = "sha256-b+9bwJ87VV6rbOPobkwMkDXGH34STjYPlt8wCRR5tEc=";
    };
  };
  zsh-nix-shell = {
    pname = "zsh-nix-shell";
    version = "82ca15e638cc208e6d8368e34a1625ed75e08f90";
    src = fetchFromGitHub {
      owner = "chisui";
      repo = "zsh-nix-shell";
      rev = "82ca15e638cc208e6d8368e34a1625ed75e08f90";
      fetchSubmodules = false;
      sha256 = "sha256-Rtg8kWVLhXRuD2/Ctbtgz9MQCtKZOLpAIdommZhXKdE=";
    };
    date = "2023-12-31";
  };
}
