{ pkgs, ... }: {
  home.packages = with pkgs; [
    (iosevka.override (import ./iosevka.nix))
    noto-fonts
    roboto
    # twitter-color-emoji is the fork of twemoji-color-font
    twitter-color-emoji
    material-design-icons
  ];

  fonts.fontconfig = {
    defaultFonts = {
      sansSerif = [
        "Roboto"
        "Noto Sans"
        "Noto Sans Adlam"
        "Noto Sans Anatolian Hieroglyphs"
        "Noto Sans Arabic"
        "Noto Sans Armenian"
        "Noto Sans Avestan"
        "Noto Sans Balinese"
        "Noto Sans Bamum"
        "Noto Sans Bassa Vah"
        "Noto Sans Batak"
        "Noto Sans Bengali"
        "Noto Sans Bhaiksuki"
        "Noto Sans Brahmi"
        "Noto Sans Buginese"
        "Noto Sans Buhid"
        "Noto Sans Canadian Aboriginal"
        "Noto Sans Carian"
        "Noto Sans Caucasian Albanian"
        "Noto Sans Chakma"
        "Noto Sans Cham"
        "Noto Sans Cherokee"
        "Noto Sans Chorasmian"
        "Noto Sans Coptic"
        "Noto Sans Cuneiform"
        "Noto Sans Cypriot"
        "Noto Sans Cypro Minoan"
        "Noto Sans Deseret"
        "Noto Sans Devanagari"
        "Noto Sans Duployan"
        "Noto Sans Egyptian Hieroglyphs"
        "Noto Sans Elbasan"
        "Noto Sans Elymaic"
        "Noto Sans Ethiopic"
        "Noto Sans Georgian"
        "Noto Sans Glagolitic"
        "Noto Sans Gothic"
        "Noto Sans Grantha"
        "Noto Sans Gujarati"
        "Noto Sans Gunjala Gondi"
        "Noto Sans Gurmukhi"
        "Noto Sans Hanifi Rohingya"
        "Noto Sans Hanunoo"
        "Noto Sans Hatran"
        "Noto Sans Hebrew"
        "Noto Sans Imperial Aramaic"
        "Noto Sans Indic Siyaq Numbers"
        "Noto Sans Inscriptional Pahlavi"
        "Noto Sans Inscriptional Parthian"
        "Noto Sans Javanese"
        "Noto Sans Kaithi"
        "Noto Sans Kannada"
        "Noto Sans Kawi"
        "Noto Sans Kayah Li"
        "Noto Sans Kharoshthi"
        "Noto Sans Khmer"
        "Noto Sans Khojki"
        "Noto Sans Khudawadi"
        "Noto Sans Lao Looped"
        "Noto Sans Lao"
        "Noto Sans Lepcha"
        "Noto Sans Limbu"
        "Noto Sans Linear A"
        "Noto Sans Linear B"
        "Noto Sans Lisu"
        "Noto Sans Lycian"
        "Noto Sans Lydian"
        "Noto Sans Mahajani"
        "Noto Sans Malayalam"
        "Noto Sans Mandaic"
        "Noto Sans Manichaean"
        "Noto Sans Marchen"
        "Noto Sans Masaram Gondi"
        "Noto Sans Math"
        "Noto Sans Mayan Numerals"
        "Noto Sans Medefaidrin"
        "Noto Sans Meetei Mayek"
        "Noto Sans Mende Kikakui"
        "Noto Sans Meroitic"
        "Noto Sans Miao"
        "Noto Sans Modi"
        "Noto Sans Mongolian"
        "Noto Sans Mono"
        "Noto Sans Mro"
        "Noto Sans Multani"
        "Noto Sans Myanmar"
        "Noto Sans Nabataean"
        "Noto Sans Nag Mundari"
        "Noto Sans Nandinagari"
        "Noto Sans New Tai Lue"
        "Noto Sans Newa"
        "Noto Sans NKo Unjoined"
        "Noto Sans NKo"
        "Noto Sans Nushu"
        "Noto Sans Ogham"
        "Noto Sans Ol Chiki"
        "Noto Sans Old Hungarian"
        "Noto Sans Old Italic"
        "Noto Sans Old North Arabian"
        "Noto Sans Old Permic"
        "Noto Sans Old Persian"
        "Noto Sans Old Sogdian"
        "Noto Sans Old South Arabian"
        "Noto Sans Old Turkic"
        "Noto Sans Oriya"
        "Noto Sans Osage"
        "Noto Sans Osmanya"
        "Noto Sans Pahawh Hmong"
        "Noto Sans Palmyrene"
        "Noto Sans Pau Cin Hau"
        "Noto Sans PhagsPa"
        "Noto Sans Phoenician"
        "Noto Sans Psalter Pahlavi"
        "Noto Sans Rejang"
        "Noto Sans Runic"
        "Noto Sans Samaritan"
        "Noto Sans Saurashtra"
        "Noto Sans Sharada"
        "Noto Sans Shavian"
        "Noto Sans Siddham"
        "Noto Sans SignWriting"
        "Noto Sans Sinhala"
        "Noto Sans Sogdian"
        "Noto Sans Sora Sompeng"
        "Noto Sans Soyombo"
        "Noto Sans Sundanese"
        "Noto Sans Syloti Nagri"
        "Noto Sans Symbols 2"
        "Noto Sans Symbols"
        "Noto Sans Syriac Eastern"
        "Noto Sans Syriac Western"
        "Noto Sans Syriac"
        "Noto Sans Tagalog"
        "Noto Sans Tagbanwa"
        "Noto Sans Tai Le"
        "Noto Sans Tai Tham"
        "Noto Sans Tai Viet"
        "Noto Sans Takri"
        "Noto Sans Tamil Supplement"
        "Noto Sans Tamil"
        "Noto Sans Tangsa"
        "Noto Sans Telugu"
        "Noto Sans Test"
        "Noto Sans Thaana"
        "Noto Sans Thai Looped"
        "Noto Sans Thai"
        "Noto Sans Tifinagh Adrar"
        "Noto Sans Tifinagh Agraw Imazighen"
        "Noto Sans Tifinagh Ahaggar"
        "Noto Sans Tifinagh Air"
        "Noto Sans Tifinagh APT"
        "Noto Sans Tifinagh Azawagh"
        "Noto Sans Tifinagh Ghat"
        "Noto Sans Tifinagh Hawad"
        "Noto Sans Tifinagh Rhissa Ixa"
        "Noto Sans Tifinagh SIL"
        "Noto Sans Tifinagh Tawellemmet"
        "Noto Sans Tifinagh"
        "Noto Sans Tirhuta"
        "Noto Sans Ugaritic"
        "Noto Sans Vai"
        "Noto Sans Vithkuqi"
        "Noto Sans Wancho"
        "Noto Sans Warang Citi"
        "Noto Sans Yi"
        "Noto Sans Zanabazar Square"
      ];
      serif = [
        "Noto Serif"
        "Noto Serif Ahom"
        "Noto Serif Armenian"
        "Noto Serif Balinese"
        "Noto Serif Bengali"
        "Noto Serif Devanagari"
        "Noto Serif Dives Akuru"
        "Noto Serif Dogra"
        "Noto Serif Ethiopic"
        "Noto Serif Georgian"
        "Noto Serif Grantha"
        "Noto Serif Gujarati"
        "Noto Serif Gurmukhi"
        "Noto Serif Hebrew"
        "Noto Serif Kannada"
        "Noto Serif Khitan Small Script"
        "Noto Serif Khmer"
        "Noto Serif Khojki"
        "Noto Serif Lao"
        "Noto Serif Makasar"
        "Noto Serif Malayalam"
        "Noto Serif Myanmar"
        "Noto Serif NP Hmong"
        "Noto Serif Old Uyghur"
        "Noto Serif Oriya"
        "Noto Serif Ottoman Siyaq"
        "Noto Serif Sinhala"
        "Noto Serif Tamil"
        "Noto Serif Tangut"
        "Noto Serif Telugu"
        "Noto Serif Thai"
        "Noto Serif Tibetan"
        "Noto Serif Toto"
        "Noto Serif Vithkuqi"
        "Noto Serif Yezidi"
      ];
      monospace = [
        "Iosevka Custom Extended"
        "Material Design Icons"
        "Roboto Mono"
        "Noto Sans Mono"
      ];
      emoji = [
        "Twitter Color Emoji"
      ];
    };
  };
}
