name: "Build"

on:
  push:
    branches: [nixos]
  pull_request:
    branches: [nixos]
  workflow_dispatch:

jobs:
  build:
    name: Build host ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - bmo
          - prismo
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup nix
        uses: cachix/install-nix-action@v31
      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: toino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: ags,hyprland,nix-community
      - name: Build
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
